[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.26"
optimizer = true
optimizer_runs = 200
via_ir = false
evm_version = "cancun"

[profile.default.fuzz]
runs = 256

[profile.default.invariant]
runs = 256
depth = 15

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
amoy = "${AMOY_RPC_URL}"
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"
mainnet = "${FORK_URL}"
reactive = "${REACTIVE_RPC}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
polygon_amoy = { key = "${POLYGONSCAN_API_KEY}" }
base_sepolia = { key = "${BASESCAN_API_KEY}" }